kind : pipeline
name : CI
type : docker

trigger :
  event :
    - push
    - tag

volumes :
  - name : m2cache
    host :
      path : /app/.m2
steps :

  - name : build
    image : docker-registry.c2a2.com/ujar/maven:3-openjdk-11-slim
    pull : if-not-exists
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands :
      - mvn clean compile test-compile -B  --file pom.xml -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
      - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report --batch-mode --file pom.xml -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD
    when :
      event :
        - push
        - tag

  - name : publish-snapshot-jar
    depends_on :
      - build
    image : docker-registry.c2a2.com/ujar/maven:3-openjdk-11-slim
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands :
      - echo Temporary disabled
     # - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Dcodegen.skip=true -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -DaltDeploymentRepository=ujar-snapshots-repository::default::https://nexus.c2a2.com/repository/maven-snapshots
    when :
      branch :
        include :
          - "feature/*"
          - "develop"
          - "*.*.x"

  - name : publish-release-jar
    depends_on :
      - build
    image : docker-registry.c2a2.com/ujar/maven:3-openjdk-11-slim
    pull : if-not-exists
    volumes :
      - name : m2cache
        path : /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands :
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -s ../maven-settings.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -DaltDeploymentRepository=ujar-releases-repository::default::https://nexus.c2a2.com/repository/maven-releases -XX:+AllowRedefinitionToAddDeleteMethods
    when :
      ref :
        - "refs/tags/*"

  - name : build-container-with-feature
    depends_on :
      - publish-snapshot-jar
    image : plugins/docker
    settings :
      dockerfile : ./.drone/c2a2/Dockerfile
      context : ./
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/jh-petclinic-vuewebflux
      registry : docker-registry.c2a2.com
      tags :
        - ${DRONE_BRANCH:22}
    when :
      branch :
        include :
          - "feature/containerized-*"

  - name : build-container-release-image
    depends_on :
      - publish-release-jar
    image : plugins/docker
    settings :
      dockerfile : ./.drone/c2a2/Dockerfile
      context : ./
      storage_driver : vfs
      username :
        from_secret : DOCKER_USERNAME
      password :
        from_secret : DOCKER_PASSWORD
      repo : docker-registry.c2a2.com/ujar/jh-petclinic-vuewebflux
      registry : docker-registry.c2a2.com
      tags :
        - ${DRONE_TAG}
        - "latest"
    when :
      ref :
        - "refs/tags/*"

---

kind : pipeline
name : CreateReleaseManually
type : docker
trigger :
  event :
    - custom
  branch :
    - "develop"
    - "*.*.x"

volumes :
  - name : m2cache
    host :
      path : /app/.m2

steps :
  - name : create-release-tag
    image : docker-registry.c2a2.com/ujar/maven:3-openjdk-11-slim
    pull : if-not-exists
    volumes :
      - name : m2cache
        path : /root/.m2
    commands :
      - echo Prepare new version ${TAG}
      - mkdir ${TAG}
      - rmdir ${TAG}
      - export NEXT_SNAPSHOT=$(increment_version -${INCREMENT_TYPE} ${TAG})-SNAPSHOT
      - export GIT_AUTHOR_NAME=$${SVC_BUILD_GIT_USERNAME}
      - export GIT_AUTHOR_EMAIL=$${SVC_BUILD_GIT_EMAIL}
      - export GIT_COMMITTER_NAME=$${SVC_BUILD_GIT_USERNAME}
      - export GIT_COMMITTER_EMAIL=$${SVC_BUILD_GIT_EMAIL}
      - git remote set-url --push origin ${DRONE_GIT_SSH_URL}
      - git checkout -b v${TAG}
      - mvn versions:set -DremoveSnapshot
      - mvn versions:set -DnewVersion=${TAG}
      - mvn versions:update-parent
      - >-
        git commit -a -m "feat: bump version to $${TAG}"
      - git tag ${TAG} && git push origin ${TAG}
      - echo "✅ Release tag ${TAG} was created."
      - sleep 10
      - git tag -d ${TAG} && git checkout ${DRONE_COMMIT_BRANCH} && git branch -D v${TAG}
      - mvn versions:set -DnewVersion=$${NEXT_SNAPSHOT}
      - mvn versions:update-parent -DallowSnapshots=true
      - >-
        git commit -a -m "feat: create new $${NEXT_SNAPSHOT}"
      - git push origin ${DRONE_COMMIT_BRANCH}
      - echo "✅ Started $${NEXT_SNAPSHOT}."
      - echo "🚀 Good job, new version ${TAG} was released successfully."
